name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. DockerHub 로그인
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker 빌드 및 푸시
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/readingtown-fastapi:latest

      # 4. EC2에 SSH 접속해서 배포
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e  # 에러 발생 시 즉시 종료
            cd /home/ubuntu/readingtown

            # 환경 변수 파일 생성
            sudo touch .env
            echo "${{ secrets.ENV_PROD }}" | sudo tee .env > /dev/null
            
            # 기존 컨테이너 종료 및 제거
            sudo docker rm -f fastapi || true

            # 최신 이미지 pull
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/readingtown-fastapi:latest

            # docker compose 실행
            docker compose -f docker-compose-fastapi.yml up -d

            # 사용하지 않는 이미지 정리
            docker image prune -f